(function(){
  const BASE_CATALOGO = Array.isArray(window.CATALOGO_PRODUCTOS) ? window.CATALOGO_PRODUCTOS : [];
  const LS_CAT='am_cotizador_catalogo_v1', LS_CART='am_cotizador_carrito_v1', LS_META='am_cotizador_meta_v1', LS_CLIENT='am_cotizador_cliente_v1';
  const $=id=>document.getElementById(id);
  const texto=v=>(v??'').toString().trim();
  const money=n=>(Number(n)||0).toLocaleString('es-MX',{style:'currency',currency:'MXN'});
  const esc=s=>texto(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const norm=s=>texto(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  const skuP=p=>texto(p.sku||p.SKU||p.CLAVE||p.clave||p['Variant SKU']);
  const nombreP=p=>texto(p.nombre||p.pieza||p.descripcion||p.DESCRIPCION||p.Descripcion||p.title||'Producto');
  const num=v=>{ if(typeof v==='number') return v; const s=texto(v).replace(/[$,\s]/g,'').replace(/[^0-9.-]/g,''); return Number(s)||0; };
  let catalogo = cargarCatalogo();
  let resultados=[...catalogo], pagina=1, porPagina=50;
  let favoritos=JSON.parse(localStorage.getItem('am_favoritos_local')||'[]');
  let carrito=JSON.parse(localStorage.getItem(LS_CART)||'[]');
  let productoPendiente=null;

  function cargarCatalogo(){ try{const saved=JSON.parse(localStorage.getItem(LS_CAT)||'null'); if(Array.isArray(saved)&&saved.length) return saved;}catch(e){} return BASE_CATALOGO; }
  function guardarCarrito(){ localStorage.setItem(LS_CART, JSON.stringify(carrito)); actualizarBadges(); renderCotizacion(); renderCatalogo(); }
  function precioProducto(p){ return num(p.precio_publico||p.precio_cliente||p.precio||p.PRECIO||p['PRECIO C/IVA']||p['IMPORTE C/IVA']||p['TOTAL C/IVA']); }
  function obtenerImagen(p){ const sku=skuP(p); return p.imagen || (Array.isArray(p.imagenes)&&p.imagenes[0]) || `imagenes/${encodeURIComponent(sku)}.jpg`; }
  function textoBusqueda(p){ return norm([skuP(p),nombreP(p),p.pieza,p.descripcion,p.categoria,p.marca,p.modelo,p.anio,p.handle].join(' ')); }
  function indice(){ return catalogo.map((p,i)=>({i, sku:norm(skuP(p)), txt:textoBusqueda(p)})); }
  function actualizarBadges(){ $('totalProductos').textContent=`${catalogo.length.toLocaleString('es-MX')} productos`; $('totalCot').textContent=`${carrito.reduce((a,x)=>a+(Number(x.cantidad)||0),0)} cotización`; const meta=JSON.parse(localStorage.getItem(LS_META)||'{}'); $('listaVigente').textContent=meta.fecha?`Lista ${meta.fecha}`:'Lista base'; $('ultimaActualizacion').textContent=meta.fecha?`Última actualización: ${meta.fecha} · ${meta.total||catalogo.length} productos`:'Sin actualización cargada.'; }
  function llenarMarcas(){ const marcas=[...new Set(catalogo.map(p=>texto(p.marca)).filter(Boolean))].sort((a,b)=>a.localeCompare(b)); $('filtroMarca').innerHTML='<option value="">Todas las marcas</option>'+marcas.map(m=>`<option value="${esc(m)}">${esc(m)}</option>`).join(''); }
  function buscar(){ const q=norm($('buscador').value), marca=norm($('filtroMarca').value); pagina=1; const ind=indice(); let ids=!q?ind.map(x=>x.i):ind.filter(x=>{const parts=q.split(/\s+/).filter(Boolean); return x.sku===q || parts.every(t=>x.txt.includes(t));}).map(x=>x.i); resultados=ids.map(i=>catalogo[i]).filter(p=>!marca||norm(p.marca)===marca); renderCatalogo(); }
  function card(p, modo='catalogo'){ const sku=skuP(p), nombre=nombreP(p), existencia=texto(p.existencia||p.EXIST||p.Exist||p.existencia_total||'0'), precio=precioProducto(p); const en=carrito.some(x=>x.sku===sku); const stock=Number(existencia)>0; return `<article class="card"><img class="thumb" loading="lazy" src="${esc(obtenerImagen(p))}" onerror="this.onerror=null;this.src='img/no-image.png';"><div><div class="sku">${esc(sku)}</div><div class="title">${esc(nombre)}</div><div class="desc">${esc(p.descripcion||p.categoria||'')}</div><div class="meta">${p.marca?esc(p.marca)+' · ':''}${p.modelo?esc(p.modelo)+' · ':''}<span class="pill ${stock?'green':'red'}">Existencia: ${esc(existencia)}</span></div><div class="price">${money(precio)}</div><div class="actions"><button class="btnSmall ${en?'btnGreen':'btn'}" onclick="AMCotizador.pedirCantidad('${esc(sku)}')">${en?'Agregar más':'Agregar'}</button></div></div></article>`; }
  function renderCatalogo(){ porPagina=parseInt($('porPagina').value,10)||50; const total=resultados.length, pags=Math.max(1,Math.ceil(total/porPagina)); if(pagina>pags) pagina=pags; const ini=(pagina-1)*porPagina, vis=resultados.slice(ini,ini+porPagina); $('gridProductos').innerHTML=vis.length?vis.map(p=>card(p)).join(''):'<div class="empty">No encontré productos con esa búsqueda.</div>'; $('resumenBusqueda').textContent=`${total.toLocaleString('es-MX')} resultado(s). Mostrando ${vis.length} en página ${pagina} de ${pags}.`; $('paginacion').innerHTML=`<button class="btnNeutral" ${pagina<=1?'disabled':''} onclick="AMCotizador.cambiarPagina(-1)">Anterior</button><span class="pill">Página ${pagina} / ${pags}</span><button class="btnNeutral" ${pagina>=pags?'disabled':''} onclick="AMCotizador.cambiarPagina(1)">Siguiente</button>`; }
  function renderFavoritos(){ const arr=catalogo.filter(p=>favoritos.includes(skuP(p))); $('gridFavoritos').innerHTML=arr.length?arr.map(p=>card(p,'favoritos')).join(''):'<div class="empty">Aún no tienes favoritos.</div>'; }
  function renderCotizacion(){ const body=$('tablaCotizacion'); if(!carrito.length){body.innerHTML='<tr><td colspan="6" class="empty">Aún no tienes productos en cotización.</td></tr>'; $('totalGeneral').textContent=money(0); return;} let total=0; body.innerHTML=carrito.map(item=>{const p=catalogo.find(x=>skuP(x)===item.sku)||item; const precio=Number(item.precio)||precioProducto(p); const cant=Number(item.cantidad)||1; const subtotal=precio*cant; total+=subtotal; return `<tr><td><b>${esc(item.sku)}</b></td><td>${esc(item.nombre||nombreP(p))}</td><td><input type="number" min="1" value="${cant}" onchange="AMCotizador.cambiarCantidad('${esc(item.sku)}',this.value)"></td><td>${money(precio)}</td><td><b>${money(subtotal)}</b></td><td><button class="btnSmall btnRed" onclick="AMCotizador.quitar('${esc(item.sku)}')">Quitar</button></td></tr>`;}).join(''); $('totalGeneral').textContent=money(total); }
  function pedirCantidad(sku){ productoPendiente=catalogo.find(p=>skuP(p)===sku); if(!productoPendiente) return; $('modalTitle').textContent=sku+' · '+nombreP(productoPendiente); $('modalDesc').textContent='Precio cliente: '+money(precioProducto(productoPendiente)); $('modalCantidad').value=1; $('cantidadModal').classList.remove('hidden'); setTimeout(()=>$('modalCantidad').focus(),50); }
  function confirmarAgregar(){ if(!productoPendiente) return; const sku=skuP(productoPendiente), cant=Math.max(1,Number($('modalCantidad').value)||1), precio=precioProducto(productoPendiente); const ex=carrito.find(x=>x.sku===sku); if(ex){ ex.cantidad=(Number(ex.cantidad)||1)+cant; ex.precio=precio; } else carrito.push({sku,nombre:nombreP(productoPendiente),cantidad:cant,precio,lista:$('listaCliente').value}); $('cantidadModal').classList.add('hidden'); guardarCarrito(); showTab('cotizacion'); }
  function copiarCotizacion(){ const cliente=texto($('clienteNombre').value)||'Cliente'; const vendedor=texto($('vendedorNombre').value)||'Vendedor'; let total=0; const lines=carrito.map(x=>{const sub=(Number(x.precio)||0)*(Number(x.cantidad)||1); total+=sub; return `${x.sku} | ${x.nombre} | Cant: ${x.cantidad} | Precio: ${money(x.precio)} | Total: ${money(sub)}`;}); const txt=`Cotización AM Autopartes\nCliente: ${cliente}\nVendedor: ${vendedor}\nLista: ${$('listaCliente').selectedOptions[0].textContent}\n\n${lines.join('\n')}\n\nTOTAL: ${money(total)}`; navigator.clipboard?.writeText(txt); alert('Cotización copiada.'); }
  function showTab(id){ document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id)); document.querySelectorAll('.tabPanel').forEach(p=>p.classList.toggle('hidden',p.id!==id)); renderCotizacion(); }
  function mapExcelRow(row){ const keys=Object.keys(row); const get=(patterns)=>{const k=keys.find(k=>patterns.some(p=>norm(k).includes(p))); return k?row[k]:''}; const sku=get(['clave','sku','codigo']); if(!texto(sku)) return null; const desc=get(['descripcion','descrip','producto','pieza']); const exist=get(['exist','existencia']); let precio40=get(['40 c/iva','40% c/iva','40 con iva']); let precio35=get(['35 c/iva','35% c/iva','35 con iva']); let precio=get(['importe c/iva','total c/iva','precio c/iva','precio']); if(!precio && precio40) precio=precio40; return {sku:texto(sku),nombre:texto(desc)||texto(sku),pieza:texto(desc)||texto(sku),descripcion:texto(desc),existencia:texto(exist||0),precio:num(precio),precio_40:num(precio40),precio_35:num(precio35),marca:texto(get(['marca'])),modelo:texto(get(['modelo'])),anio:texto(get(['año','anio']))}; }
  async function cargarExcel(file){ if(!file) return; $('uploadResumen').className='warn'; $('uploadResumen').textContent='Leyendo archivo...'; const data=await file.arrayBuffer(); const wb=XLSX.read(data,{type:'array'}); let rows=[]; wb.SheetNames.forEach(name=>{ const sheet=XLSX.utils.sheet_to_json(wb.Sheets[name],{defval:''}); rows=rows.concat(sheet); }); const mapped=rows.map(mapExcelRow).filter(Boolean); const unique=[]; const seen=new Set(); mapped.forEach(p=>{if(!seen.has(p.sku)){seen.add(p.sku); unique.push(p);}}); if(!unique.length){ $('uploadResumen').className='warn'; $('uploadResumen').textContent='No pude detectar productos. Revisa que el Excel tenga columna CLAVE/SKU.'; return; } catalogo=unique; resultados=[...catalogo]; localStorage.setItem(LS_CAT, JSON.stringify(catalogo)); const meta={fecha:new Date().toLocaleString('es-MX'), total:catalogo.length, archivo:file.name}; localStorage.setItem(LS_META, JSON.stringify(meta)); $('uploadResumen').className='ok'; $('uploadResumen').textContent=`Lista cargada: ${file.name}. Productos detectados: ${catalogo.length.toLocaleString('es-MX')}.`; $('gerenteResumen').textContent=$('uploadResumen').textContent; llenarMarcas(); actualizarBadges(); buscar(); }
  function descargarJson(){ const blob=new Blob([JSON.stringify(catalogo,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='catalogo_am_actualizado.json'; a.click(); URL.revokeObjectURL(a.href); }
  function init(){ const savedClient=JSON.parse(localStorage.getItem(LS_CLIENT)||'{}'); $('clienteNombre').value=savedClient.cliente||''; $('vendedorNombre').value=savedClient.vendedor||''; $('listaCliente').value=savedClient.lista||'40'; ['clienteNombre','vendedorNombre','listaCliente'].forEach(id=>$(id).addEventListener('change',()=>{localStorage.setItem(LS_CLIENT,JSON.stringify({cliente:$('clienteNombre').value,vendedor:$('vendedorNombre').value,lista:$('listaCliente').value})); renderCatalogo(); renderCotizacion();})); $('buscador').addEventListener('input', buscar); $('limpiarBusqueda').addEventListener('click',()=>{$('buscador').value='';buscar();}); $('filtroMarca').addEventListener('change',buscar); $('porPagina').addEventListener('change',()=>{pagina=1;renderCatalogo();}); $('copiarCotizacion').addEventListener('click',copiarCotizacion); $('vaciarCotizacion').addEventListener('click',()=>{if(confirm('¿Vaciar cotización?')){carrito=[];guardarCarrito();}}); $('limpiarCotizador').addEventListener('click',()=>{carrito=[];guardarCarrito();}); $('excelInput').addEventListener('change',e=>cargarExcel(e.target.files[0])); $('restaurarCatalogo').addEventListener('click',()=>{if(confirm('¿Restaurar catálogo base?')){localStorage.removeItem(LS_CAT);localStorage.removeItem(LS_META);catalogo=BASE_CATALOGO;resultados=[...catalogo];llenarMarcas();actualizarBadges();buscar();}}); $('descargarJson').addEventListener('click',descargarJson); $('cancelarAgregar').addEventListener('click',()=>$('cantidadModal').classList.add('hidden')); $('confirmarAgregar').addEventListener('click',confirmarAgregar); document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab))); llenarMarcas(); actualizarBadges(); buscar(); renderCotizacion(); }
  window.AMCotizador={cambiarPagina(d){pagina+=d;renderCatalogo();scrollTo({top:0,behavior:'smooth'});},pedirCantidad, cambiarCantidad(sku,v){const item=carrito.find(x=>x.sku===sku); if(item){item.cantidad=Math.max(1,Number(v)||1); guardarCarrito();}}, quitar(sku){carrito=carrito.filter(x=>x.sku!==sku);guardarCarrito();}};
  init();
})();
